// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkiYPT8VJAddx-nW2gmt1bWxSK8lBm3S0',
    appId: '1:326116460647:web:59454782178d39da642cc2',
    messagingSenderId: '326116460647',
    projectId: 'tt-scoreboard-aa76b',
    authDomain: 'tt-scoreboard-aa76b.firebaseapp.com',
    storageBucket: 'tt-scoreboard-aa76b.firebasestorage.app',
    measurementId: 'G-M3QGX1BDCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN4UdpUFe1a6vTX-fDzarD9ago6oKLxiY',
    appId: '1:326116460647:android:f9691188b150a93a642cc2',
    messagingSenderId: '326116460647',
    projectId: 'tt-scoreboard-aa76b',
    storageBucket: 'tt-scoreboard-aa76b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpNCsU3SHiDLPg3P2gg9f08DyCQlkeC4',
    appId: '1:326116460647:ios:69697f45dd84ada8642cc2',
    messagingSenderId: '326116460647',
    projectId: 'tt-scoreboard-aa76b',
    storageBucket: 'tt-scoreboard-aa76b.firebasestorage.app',
    iosBundleId: 'com.example.tableTennisScoreboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkpNCsU3SHiDLPg3P2gg9f08DyCQlkeC4',
    appId: '1:326116460647:ios:69697f45dd84ada8642cc2',
    messagingSenderId: '326116460647',
    projectId: 'tt-scoreboard-aa76b',
    storageBucket: 'tt-scoreboard-aa76b.firebasestorage.app',
    iosBundleId: 'com.example.tableTennisScoreboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkiYPT8VJAddx-nW2gmt1bWxSK8lBm3S0',
    appId: '1:326116460647:web:def97ab3bef38baf642cc2',
    messagingSenderId: '326116460647',
    projectId: 'tt-scoreboard-aa76b',
    authDomain: 'tt-scoreboard-aa76b.firebaseapp.com',
    storageBucket: 'tt-scoreboard-aa76b.firebasestorage.app',
    measurementId: 'G-5QQP50MBJF',
  );
}
